import { Language } from "../types";

export const translations = {
  en: {
    brandName: "KISSS",
    brandTagline: "Know Yourself First.",
    chooseYourBook: "Choose your book",
    interactiveStoryLesson: "Interactive Story Lesson",
    missionBadge: "Our Mission",
    missionHeading: "You are not just buying a coloring book.",
    missionP1: "You are helping place a child development resource into the hands of more children.",
    missionP2: "KISSS — Keep It Simple Simon Series — helps children begin with one of life's most important lessons: knowing themselves first.",
    missionP3: "Through simple words, pictures, and coloring activities, children are gently guided to understand who they are, how they feel, how they choose, and how they grow.",
    missionP4: "And with every purchase, the small profit goes back into buying more books, so more children can receive the same opportunity to learn, color, and grow from the inside out.",
    missionClose: "KISSS is more than a book. It is a seed planted in a child's life.",
    modeStudent: "Student Adventure",
    modeParent: "Parent Dashboard",
    points: "Stars",
    grade: "Grade",
    selectTopic: "Choose a Learning Treasure",
    customTopic: "Or Enter any Custom Topic Your Child Struggles With...",
    generateBtn: "Generate AI Micro-Lesson 🪄",
    generating: "Gathering magic scrolls from the clouds... Please wait!",
    keyTakeaways: "💡 Magical Takeaways",
    startQuiz: "🎯 Play Knowledge Challenge",
    retakeQuiz: "🔄 Replay Quiz",
    questionOf: "Question",
    parentGateTitle: "Parent Safeguard Puzzle",
    parentGateDetail: "To access the secure dashboard, please solve this logic puzzle to prove you are an adult:",
    parentGatePlaceholder: "Type your answer...",
    verify: "Verify",
    parentGateError: "Oops! Let's try another magic math puzzle.",
    recentPerformance: "📊 Recent Learning Adventures",
    noAdventure: "No learning quests completed yet. Go to Student mode to start a quest!",
    parentAdviceTitle: "✨ AI Actionable At-Home Advice",
    generatePlayBtn: "Analyze & Generate 5-Min Hands-On Game 🎈",
    activityInstructions: "Play Instructions",
    proTip: "Parenting Pro-Tip",
    materials: "What you need",
    gradeLevel: "Select target level",
    studentProfile: "Student Profile",
    childNameLabel: "Child's Name",
    saveProfile: "Save Profile",
    saved: "Saved!",
    viewActivity: "Open Play Guide",
    noHistorySelect: "Select an adventure below to generate customized at-home offline games!",
    avatarSelect: "Choose Your Hero Guide",
    customTopicPlaceholder: "e.g., Simple Long Division, Why do leaves change color, English vowel blends...",
    quizCompleted: "Quest Complete!",
    quizCompletedScore: "You earned",
    scoreWord: "Score",
    congratsTitle: "Sensational Effort! 🎉",
    correctWord: "Correct!",
    incorrectWord: "Not quite, but trying teaches you!",
    nextQuestion: "Next Question ➡️",
    claimStars: "Claim Stars! ⭐️",
    parentDashboardIntro: "Empowering parents with tailored physical games to bridge conceptual gaps without screen-time.",
    coLearningTitle: "🤝 Screen-Free Co-Learning Challenge",
    coLearningMastering: "Mastering Concept",
    coLearningItems: "Common Household Items to Gather",
    coLearningScript: "🗣️ Simple Parent Helper Script",
    coLearningScriptDesc: "Use these friendly verbal cues to guide your child without taking over the challenge:",
    coLearningReflection: "🤔 End Reflection Prompt",
    coLearningReflectionDesc: "Ask your child this question at the end to lock in the memory:",
    coLearningUserPrompt: "Concept you are reinforcing",
    landingHeroTitle: "Turn Screen-Time Gaps into Offline Connection",
    landingHeroSubtitle: "An encouraging, parent-guided AI learning companion. Children complete enchanting quiz quests, while parents get custom offline 5-Min hands-on games to bridge learning hurdles together.",
    landingBtnTest: "Launch Interactive Sandbox 🎮",
    landingFeatureTitle: "Designed for Modern Families, Rooted in Science",
    landingFeature1Title: "✨ Screen-Safe Quests",
    landingFeature1Desc: "Custom bitesize generated lessons & quizzes personalized to your child's grade level and interest.",
    landingFeature2Title: "🤝 Co-Learning Offline Games",
    landingFeature2Desc: "Hurdles identified from student answers immediately compile into real-world physical games using spoons, cups, and pebbles.",
    landingFeature3Title: "📈 Actionable Dashboards",
    landingFeature3Desc: "Clean parent oversight, detailed diagnostic history, and beautiful custom conversational script cues.",
    landingHowItWorksTitle: "How to Test in the Sandbox Simulator:",
    landingHowStep1: "1. Select a Topic as a Student in the Adventure panel.",
    landingHowStep2: "2. Finish the short quiz to log scores into the learning engine.",
    landingHowStep3: "3. Flip to 'Parent Dashboard' using the top bar (complete the safety gate puzzle!).",
    landingHowStep4: "4. Select your quiz record to trigger the custom AI Co-Learning Challenge generation!",
    landingSandboxTitle: "Ready to Experience Screen-Free Breakthroughs?",
    landingSandboxBtn: "Enter Live Sandbox Workspace",
    landingTestimonial: "“My daughter struggled with division for weeks. One round of KISSS's 5-minute teaspoon physical dividing game made it click. Incredible tool!” — Sarah, Mum of a 3rd grader",
    gradeOptions: {
      "kindergarten": "Kindergarten",
      "1st": "1st Grade",
      "2nd": "2nd Grade",
      "3rd": "3rd Grade",
      "4th": "4th Grade",
      "5th": "5th Grade"
    }
  },
  es: {
    brandName: "KISSS",
    brandTagline: "Conócete a Ti Mismo Primero.",
    chooseYourBook: "Elige tu libro",
    interactiveStoryLesson: "Lección de Cuento Interactivo",
    missionBadge: "Nuestra Misión",
    missionHeading: "No solo estás comprando un libro para colorear.",
    missionP1: "Estás ayudando a poner un recurso para el desarrollo infantil en las manos de más niños.",
    missionP2: "KISSS — Keep It Simple Simon Series — ayuda a los niños a comenzar con una de las lecciones más importantes de la vida: conocerse a sí mismos primero.",
    missionP3: "A través de palabras sencillas, imágenes y actividades para colorear, los niños son guiados con cariño para entender quiénes son, cómo se sienten, cómo eligen y cómo crecen.",
    missionP4: "Y con cada compra, la pequeña ganancia se reinvierte en comprar más libros, para que más niños reciban la misma oportunidad de aprender, colorear y crecer desde adentro hacia afuera.",
    missionClose: "KISSS es más que un libro. Es una semilla plantada en la vida de un niño.",
    modeStudent: "Aventura del Estudiante",
    modeParent: "Panel Parental",
    points: "Estrellas",
    grade: "Grado",
    selectTopic: "Elige un Tesoro de Aprendizaje",
    customTopic: "O ingresa cualquier tema difícil con el que tu hijo batalle...",
    generateBtn: "Generar Micro-Lección con IA 🪄",
    generating: "Reuniendo pergaminos mágicos de las nubes... ¡Espera un momento!",
    keyTakeaways: "💡 Sabiduría Clave",
    startQuiz: "🎯 Jugar Desafío del Conocimiento",
    retakeQuiz: "🔄 Volver a Jugar Quiz",
    questionOf: "Pregunta",
    parentGateTitle: "Acertijo de Seguridad para Padres",
    parentGateDetail: "Para entrar al panel seguro, resuelve este rompecabezas lógico para demostrar que eres adulto:",
    parentGatePlaceholder: "Escribe tu respuesta...",
    verify: "Verificar",
    parentGateError: "¡Uy! Probemos con otro acertijo matemático mágico.",
    recentPerformance: "📊 Aventuras Recientes de Aprendizaje",
    noAdventure: "Aún no se completan misiones. ¡Ve al modo Estudiante para comenzar!",
    parentAdviceTitle: "✨ Consejos Prácticos de IA para Casa",
    generatePlayBtn: "Analizar y Generar Juego de 5 Minutos 🎈",
    activityInstructions: "Instrucciones de Juego",
    proTip: "Consejo de Crianza",
    materials: "Cosas que necesitas",
    gradeLevel: "Seleccionar Grado",
    studentProfile: "Perfil del Estudiante",
    childNameLabel: "Nombre del Niño/a",
    saveProfile: "Guardar Perfil",
    saved: "¡Guardado!",
    viewActivity: "Ver Guía de Juego",
    noHistorySelect: "¡Elige una aventura a continuación para crear juegos físicos personalizados!",
    avatarSelect: "Elige tu Guía Héroe",
    customTopicPlaceholder: "ej., División larga simple, Por qué cambian de color las hojas, Diptongos y sílabas...",
    quizCompleted: "¡Misión Completada!",
    quizCompletedScore: "¡Ganaste",
    scoreWord: "Puntaje",
    congratsTitle: "¡Esfuerzo Sensacional! 🎉",
    correctWord: "¡Correcto!",
    incorrectWord: "No del todo, ¡pero intentar te hace sabio!",
    nextQuestion: "Siguiente Pregunta ➡️",
    claimStars: "¡Reclamar Estrellas! ⭐️",
    parentDashboardIntro: "Apoyando a los padres con juegos físicos listos para reforzar la escuela sin pantallas.",
    coLearningTitle: "🤝 Desafío Co-Aprendizaje Sin Pantallas",
    coLearningMastering: "Concepto en desarrollo",
    coLearningItems: "Objetos del hogar para reunir",
    coLearningScript: "🗣️ Guión de conversación para padres",
    coLearningScriptDesc: "Usa estas frases sugeridas para guiar a tu hijo sin resolver el juego por él:",
    coLearningReflection: "🤔 Pregunta de reflexión para el final",
    coLearningReflectionDesc: "Hazle esta pregunta a tu hijo al final para consolidar lo aprendido:",
    coLearningUserPrompt: "Concepto que reforzarás",
    landingHeroTitle: "Une el aprendizaje escolar con juegos familiares sin pantalla",
    landingHeroSubtitle: "Un compañero guiado por inteligencia artificial. Los niños completan misiones de quizzes divertidos, mientras que los padres reciben juegos caseros de 5 minutos offline para resolver dificultades juntos.",
    landingBtnTest: "Probar Simulador Sandbox 🎮",
    landingFeatureTitle: "Diseñado para Familias Modernas, Basado en Ciencia",
    landingFeature1Title: "✨ Quizzes Divertidos",
    landingFeature1Desc: "Micro-lecciones y acertijos adaptados con precisión al grado e interés de tu hijo/a.",
    landingFeature2Title: "🤝 Co-Aprendizaje de Juego",
    landingFeature2Desc: "Las dificultades encontradas por IA se convierten de inmediato en ingeniosos juegos físicos con cucharas u objetos.",
    landingFeature3Title: "📈 Panel Parental Claro",
    landingFeature3Desc: "Acompañamiento simple, historial detallado y guiones hablados listos para conversar sin presiones.",
    landingHowItWorksTitle: "Pasos para probar en el simulador interactivo:",
    landingHowStep1: "1. Elige un Tema de Aprendizaje con la vista de Estudiante.",
    landingHowStep2: "2. Resuelve el quiz corto para guardar el historial en la memoria del app.",
    landingHowStep3: "3. Cambia al 'Panel Parental' arriba (¡resuelve el acertijo lógico de seguridad!).",
    landingHowStep4: "4. Selecciona el registro del historial para generar el Desafío Co-Aprendizaje en tiempo real.",
    landingSandboxTitle: "¿Listo para experimentar avances sin pantallas?",
    landingSandboxBtn: "Entrar al Simulador Sandbox",
    landingTestimonial: "“Mi hija batalló con la división por semanas. Una sesión del juego físico de cucharas de KISSS lo solucionó todo. ¡Excelente!” — Sarah, Mamá de un alumno de 3er grado",
    gradeOptions: {
      "kindergarten": "Preescolar",
      "1st": "1er Grado",
      "2nd": "2do Grado",
      "3rd": "3er Grado",
      "4th": "4to Grado",
      "5th": "5to Grado"
    }
  },
  fr: {
    brandName: "KISSS",
    brandTagline: "Connais-Toi Toi-Même d'Abord.",
    chooseYourBook: "Choisis ton livre",
    interactiveStoryLesson: "Leçon d'Histoire Interactive",
    missionBadge: "Notre Mission",
    missionHeading: "Vous n'achetez pas seulement un livre de coloriage.",
    missionP1: "Vous aidez à mettre une ressource de développement de l'enfant entre les mains de plus d'enfants.",
    missionP2: "KISSS — Keep It Simple Simon Series — aide les enfants à commencer par l'une des leçons les plus importantes de la vie : se connaître soi-même d'abord.",
    missionP3: "À travers des mots simples, des images et des activités de coloriage, les enfants sont guidés avec douceur pour comprendre qui ils sont, ce qu'ils ressentent, comment ils choisissent et comment ils grandissent.",
    missionP4: "Et à chaque achat, le petit bénéfice sert à acheter plus de livres, afin que plus d'enfants reçoivent la même chance d'apprendre, de colorier et de grandir de l'intérieur.",
    missionClose: "KISSS est plus qu'un livre. C'est une graine plantée dans la vie d'un enfant.",
    modeStudent: "Aventure de l'Élève",
    modeParent: "Tableau de Bord des Parents",
    points: "Étoiles",
    grade: "Niveau",
    selectTopic: "Choisis un Trésor d'Apprentissage",
    customTopic: "Ou saisis un sujet difficile avec lequel ton enfant a du mal...",
    generateBtn: "Générer la Micro-Leçon par IA 🪄",
    generating: "Rassemblement des parchemins magiques dans les nuages... Un instant !",
    keyTakeaways: "💡 Sagesse Clé",
    startQuiz: "🎯 Lancer le Défi des Connaissances",
    retakeQuiz: "🔄 Recommencer le Quiz",
    questionOf: "Question",
    parentGateTitle: "Énigme de Sécurité Parentale",
    parentGateDetail: "Pour accéder au tableau de bord, résous cette énigme logique afin de prouver que tu es un adulte :",
    parentGatePlaceholder: "Écris ta réponse...",
    verify: "Vérifier",
    parentGateError: "Oups ! Essayons une autre énigme mathématique magique.",
    recentPerformance: "📊 Aventures d'Apprentissage Récentes",
    noAdventure: "Aucune quête effectuée pour l'instant. Va en mode Élève pour commencer !",
    parentAdviceTitle: "✨ Conseils Pratiques d'IA à la Maison",
    generatePlayBtn: "Analyser & Créer un Jeu Physique de 5 Min 🎈",
    activityInstructions: "Instructions de Jeu",
    proTip: "Conseil de Parent",
    materials: "Matériaux nécessaires",
    gradeLevel: "Sélectionner le Niveau",
    studentProfile: "Profil de l'Élève",
    childNameLabel: "Nom de l'enfant",
    saveProfile: "Sauvegarder",
    saved: "Enregistré !",
    viewActivity: "Voir le Guide de Jeu",
    noHistorySelect: "Sélectionne une aventure ci-dessous pour générer des activités de jeu personnalisées !",
    avatarSelect: "Choisis ton Guide Héros",
    customTopicPlaceholder: "ex: Division simple à un chiffre, Pourquoi les feuilles changent de couleur, Conjugaison...",
    quizCompleted: "Quête Réussie !",
    quizCompletedScore: "Tu as gagné",
    scoreWord: "Score",
    congratsTitle: "Effort Sensationnel ! 🎉",
    correctWord: "Correct !",
    incorrectWord: "Pas tout à fait, mais essayer t'apprend beaucoup !",
    nextQuestion: "Question Suivante ➡️",
    claimStars: "Réclamer mes Étoiles ! ⭐️",
    parentDashboardIntro: "Accompagner les parents avec des activités ludiques pour renforcer l'école sans écran.",
    coLearningTitle: "🤝 Défi de Co-Apprentissage Sans Écran",
    coLearningMastering: "Concept en cours de maîtrise",
    coLearningItems: "Objets de la maison à rassembler",
    coLearningScript: "🗣️ Script de conversation pour les parents",
    coLearningScriptDesc: "Utilise ces répliques bienveillantes pour guider ton enfant sans faire le travail à sa place :",
    coLearningReflection: "🤔 Question de réflexion de fin",
    coLearningReflectionDesc: "Pose cette question à ton enfant à la fin pour ancrer la notion :",
    coLearningUserPrompt: "Concept à consolider",
    landingHeroTitle: "Remplacer le temps d'écran par du jeu en famille offline",
    landingHeroSubtitle: "Un compagnon d'apprentissage par IA bienveillant. Les enfants relèvent des défis scolaires captivants, tandis que les parents reçoivent des jeux réels de 5 minutes pour surmonter les obstacles ensemble.",
    landingBtnTest: "Lancer le Sandbox Interactif 🎮",
    landingFeatureTitle: "Conçu pour les familles modernes, ancré dans la science",
    landingFeature1Title: "✨ Quêtes sans Écran Excessif",
    landingFeature1Desc: "Des cours et quiz sur mesure selon le niveau scolaire et les intérêts de votre enfant.",
    landingFeature2Title: "🤝 Co-Apprentissage Réel",
    landingFeature2Desc: "Les erreurs du quiz sont converties instantanément en petits jeux physiques avec des objets du quotidien.",
    landingFeature3Title: "📈 Suivi et Scripts Parentaux",
    landingFeature3Desc: "Contrôle simple pour les parents, historique détaillé et répliques faciles à dire pour guider sans faire à sa place.",
    landingHowItWorksTitle: "Comment tester dans le simulateur de Sandbox :",
    landingHowStep1: "1. Choisis un Sujet dans l'Aventure de l'Élève.",
    landingHowStep2: "2. Termine le court quiz pour enregistrer le score dans l'historique.",
    landingHowStep3: "3. Passe au 'Tableau de bord' en haut (en résolvant l'énigme de sécurité parentale !).",
    landingHowStep4: "4. Sélectionne la quête effectuée pour voir apparaître le Défi de Co-Apprentissage sur-mesure !",
    landingSandboxTitle: "Prêt à voir votre enfant progresser sans écran ?",
    landingSandboxBtn: "Entrer dans le simulateur interactif",
    landingTestimonial: "« Ma fille avait du mal avec la division depuis des semaines. Le jeu des petites cuillères de KISSS a tout débloqué en 5 minutes. Formidable ! » — Sarah, maman d'une élève de CE2",
    gradeOptions: {
      "kindergarten": "Maternelle",
      "1st": "CP (1ère)",
      "2nd": "CE1 (2ème)",
      "3rd": "CE2 (3ème)",
      "4th": "CM1 (4ème)",
      "5th": "CM2 (5ème)"
    }
  },
  pt: {
    brandName: "KISSS",
    brandTagline: "Conheça a Si Mesmo Primeiro.",
    chooseYourBook: "Escolha seu livro",
    interactiveStoryLesson: "Lição em História Interativa",
    missionBadge: "Nossa Missão",
    missionHeading: "Você não está apenas comprando um livro de colorir.",
    missionP1: "Você está ajudando a colocar um recurso de desenvolvimento infantil nas mãos de mais crianças.",
    missionP2: "KISSS — Keep It Simple Simon Series — ajuda as crianças a começar por uma das lições mais importantes da vida: conhecer a si mesmas primeiro.",
    missionP3: "Por meio de palavras simples, imagens e atividades de colorir, as crianças são guiadas com carinho para entender quem são, como se sentem, como escolhem e como crescem.",
    missionP4: "E a cada compra, o pequeno lucro é reinvestido na compra de mais livros, para que mais crianças recebam a mesma oportunidade de aprender, colorir e crescer de dentro para fora.",
    missionClose: "KISSS é mais do que um livro. É uma semente plantada na vida de uma criança.",
    modeStudent: "Aventura do Aluno",
    modeParent: "Painel dos Pais",
    points: "Estrelas",
    grade: "Série",
    selectTopic: "Escolha um Tesouro de Aprendizado",
    customTopic: "Ou digite qualquer tema com que seu filho tenha dificuldade...",
    generateBtn: "Gerar Microlição com IA 🪄",
    generating: "Reunindo pergaminhos mágicos das nuvens... Aguarde!",
    keyTakeaways: "💡 Aprendizados Mágicos",
    startQuiz: "🎯 Jogar o Desafio do Conhecimento",
    retakeQuiz: "🔄 Repetir o Quiz",
    questionOf: "Pergunta",
    parentGateTitle: "Enigma de Proteção dos Pais",
    parentGateDetail: "Para acessar o painel seguro, resolva este enigma de lógica para provar que você é um adulto:",
    parentGatePlaceholder: "Digite sua resposta...",
    verify: "Verificar",
    parentGateError: "Ops! Vamos tentar outro enigma matemático mágico.",
    recentPerformance: "📊 Aventuras de Aprendizado Recentes",
    noAdventure: "Nenhuma missão de aprendizado concluída ainda. Vá para o modo Aluno para começar uma missão!",
    parentAdviceTitle: "✨ Conselhos Práticos de IA para Casa",
    generatePlayBtn: "Analisar e Gerar Jogo Prático de 5 Min 🎈",
    activityInstructions: "Instruções do Jogo",
    proTip: "Dica de Ouro para Pais",
    materials: "O que você precisa",
    gradeLevel: "Selecione o nível desejado",
    studentProfile: "Perfil do Aluno",
    childNameLabel: "Nome da Criança",
    saveProfile: "Salvar Perfil",
    saved: "Salvo!",
    viewActivity: "Abrir Guia de Jogo",
    noHistorySelect: "Selecione uma aventura abaixo para gerar jogos personalizados para fazer em casa, sem tela!",
    avatarSelect: "Escolha seu Herói Guia",
    customTopicPlaceholder: "ex.: Divisão Simples, Por que as folhas mudam de cor, Sons das vogais...",
    quizCompleted: "Missão Concluída!",
    quizCompletedScore: "Você ganhou",
    scoreWord: "Pontuação",
    congratsTitle: "Esforço Sensacional! 🎉",
    correctWord: "Correto!",
    incorrectWord: "Não foi dessa vez, mas tentar já é aprender!",
    nextQuestion: "Próxima Pergunta ➡️",
    claimStars: "Resgatar Estrelas! ⭐️",
    parentDashboardIntro: "Empoderando os pais com jogos físicos personalizados para preencher lacunas de aprendizado sem tempo de tela.",
    coLearningTitle: "🤝 Desafio de Aprendizado em Família sem Tela",
    coLearningMastering: "Dominando o Conceito",
    coLearningItems: "Itens Comuns da Casa para Reunir",
    coLearningScript: "🗣️ Roteiro Simples de Apoio para os Pais",
    coLearningScriptDesc: "Use estas frases amigáveis para guiar seu filho sem assumir o controle do desafio:",
    coLearningReflection: "🤔 Pergunta de Reflexão Final",
    coLearningReflectionDesc: "Faça esta pergunta ao seu filho no final para fixar o aprendizado:",
    coLearningUserPrompt: "Conceito que você está reforçando",
    landingHeroTitle: "Transforme o Tempo de Tela em Conexão Offline",
    landingHeroSubtitle: "Um companheiro de aprendizado com IA, guiado pelos pais e cheio de incentivo. As crianças completam missões de quiz encantadoras, enquanto os pais recebem jogos práticos de 5 minutos, offline, para superar obstáculos juntos.",
    landingBtnTest: "Abrir o Simulador Interativo 🎮",
    landingFeatureTitle: "Feito para Famílias Modernas, Baseado na Ciência",
    landingFeature1Title: "✨ Missões Seguras sem Tela",
    landingFeature1Desc: "Lições e quizzes personalizados, gerados sob medida para a série e os interesses do seu filho.",
    landingFeature2Title: "🤝 Jogos de Aprendizado em Família Offline",
    landingFeature2Desc: "As dificuldades identificadas nas respostas viram jogos físicos do mundo real usando colheres, copos e pedrinhas.",
    landingFeature3Title: "📈 Painéis Práticos",
    landingFeature3Desc: "Acompanhamento claro para os pais, histórico detalhado e roteiros de conversa fáceis de usar.",
    landingHowItWorksTitle: "Como testar no Simulador Sandbox:",
    landingHowStep1: "1. Escolha um Tema como Aluno no painel de Aventura.",
    landingHowStep2: "2. Termine o quiz rápido para registrar as pontuações no sistema.",
    landingHowStep3: "3. Vá para o 'Painel dos Pais' na barra superior (resolva o enigma de segurança!).",
    landingHowStep4: "4. Selecione o resultado do quiz para gerar o Desafio de Aprendizado em Família com IA!",
    landingSandboxTitle: "Pronto para ver avanços sem tela?",
    landingSandboxBtn: "Entrar no Espaço Interativo",
    landingTestimonial: "“Minha filha teve dificuldade com divisão por semanas. Uma rodada do jogo físico de colherzinhas do KISSS, de 5 minutos, fez tudo fazer sentido. Ferramenta incrível!” — Sarah, mãe de uma aluna do 3º ano",
    gradeOptions: {
      "kindergarten": "Educação Infantil",
      "1st": "1º Ano",
      "2nd": "2º Ano",
      "3rd": "3º Ano",
      "4th": "4º Ano",
      "5th": "5º Ano"
    }
  }
};
export type TranslationType = typeof translations.en;
